"""One-shot Discover → Evaluate → Gap-audit cycle. Network optional."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from cost.loop.evaluate import evaluate_item
from cost.loop.gap_audit import audit, save_audit
from cost.loop.github_discover import discover_github
from cost.loop.pypi_discover import discover_pypi
from cost.loop.watch import url_digest, watch

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_GITHUB_FIXTURE = ROOT / "examples" / "loop" / "github_search.json"
DEFAULT_PYPI_FIXTURE = ROOT / "examples" / "loop" / "pypi.json"
QUEUE_PATH = Path(os.environ.get("COST_DISCOVER_QUEUE", "state/discover_queue.json"))
CANDIDATES_PATH = Path(os.environ.get("COST_CANDIDATES_MD", "state/candidates.md"))


def _merge_unique(batches: list[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for batch in batches:
        for item in batch:
            digest = item.get("sha256") or url_digest(str(item.get("url") or ""))
            if not digest or digest in seen:
                continue
            seen.add(digest)
            item = dict(item)
            item["sha256"] = digest
            out.append(item)
    return out


def _render_candidates(queue: list[dict[str, Any]], gaps: dict[str, Any]) -> str:
    lines = [
        "# COST next integrations",
        "",
        "Generated by `cost loop improve`. Operator reviews Monday 09:00 AEST.",
        "Auto-merge is OFF — these change classifiers, IAM graphs, or CI scanners.",
        "",
        "## Discover queue (rubric ≥ 7)",
    ]
    discover = [i for i in queue if i.get("verdict") == "discover"]
    if not discover:
        lines.append("- (none this cycle)")
    for item in discover[:20]:
        lines.append(
            f"- **{item.get('title')}** — {item.get('module_hint') or item.get('source')} "
            f"(score {item.get('score')}) {item.get('url')}"
        )
    lines.extend(["", "## Gap-audit next integrations", ""])
    for item in gaps.get("next_integrations") or []:
        lines.append(f"- **{item.get('name')}** → `{item.get('module')}` [{item.get('impact')}] {item.get('url')}")
        lines.append(f"  - {item.get('first_commit')}")
    lines.extend(["", "## Self-challenge", ""])
    for q in (gaps.get("challenge_questions") or [])[:8]:
        lines.append(f"- {q}")
    lines.append("")
    return "\n".join(lines)


def improve(
    *,
    fetch: bool = False,
    github_fixture: str | Path | None = None,
    pypi_fixture: str | Path | None = None,
    seen_path: Path | None = None,
    queue_path: Path | None = None,
    candidates_path: Path | None = None,
    audit_path: Path | None = None,
) -> dict[str, Any]:
    watched = watch(mode="all", fetch=fetch, seen_path=seen_path)
    gh_fix = github_fixture
    pypi_fix = pypi_fixture
    if not fetch:
        if gh_fix is None and DEFAULT_GITHUB_FIXTURE.exists():
            gh_fix = DEFAULT_GITHUB_FIXTURE
        if pypi_fix is None and DEFAULT_PYPI_FIXTURE.exists():
            pypi_fix = DEFAULT_PYPI_FIXTURE
    gh = discover_github(fixture=gh_fix, fetch=fetch)
    pypi = discover_pypi(fixture=pypi_fix, fetch=fetch)
    merged = _merge_unique([watched.get("items") or [], gh, pypi])
    evaluated = []
    for item in merged:
        rubric = evaluate_item(item)
        evaluated.append({**item, **rubric})
    evaluated.sort(key=lambda r: int(r.get("score") or 0), reverse=True)

    report = audit()
    qpath = queue_path or QUEUE_PATH
    qpath.parent.mkdir(parents=True, exist_ok=True)
    qpath.write_text(json.dumps({"items": evaluated}, indent=2, default=str) + "\n", encoding="utf-8")
    cpath = candidates_path or CANDIDATES_PATH
    cpath.write_text(_render_candidates(evaluated, report), encoding="utf-8")
    saved_audit = save_audit(report, audit_path)
    return {
        "forum_new": watched.get("new_count", 0),
        "github": len(gh),
        "pypi": len(pypi),
        "queued": len(evaluated),
        "discover": sum(1 for i in evaluated if i.get("verdict") == "discover"),
        "watch": sum(1 for i in evaluated if i.get("verdict") == "watch"),
        "skip": sum(1 for i in evaluated if i.get("verdict") == "skip"),
        "gaps": (report.get("summary") or {}).get("gaps"),
        "next_integrations": [i.get("id") for i in report.get("next_integrations") or []],
        "queue_path": str(qpath),
        "candidates_path": str(cpath),
        "audit_path": str(saved_audit),
    }
