#!/usr/bin/env bash
# 24/7 universe scanner: 1000 pairs, 6 timeframes, chunked rotation.
set -euo pipefail
cd "$(dirname "$0")/.."
export PYTHONPATH="${PYTHONPATH:-}:$(pwd)"

export UNIVERSE_SIZE="${UNIVERSE_SIZE:-1000}"
export CHUNK_SIZE="${CHUNK_SIZE:-25}"
export TICK_INTERVAL="${TICK_INTERVAL:-300}"
export UNIVERSE_PAPER_MAX="${UNIVERSE_PAPER_MAX:-150}"

# Cursor-hosted multi-model AI improvement (cheap first, escalate when needed)
export EW_LLM_BACKEND="${EW_LLM_BACKEND:-cursor}"
export EW_AI_IMPROVEMENT="${EW_AI_IMPROVEMENT:-1}"
export EW_IMPROVEMENT_LLM="${EW_IMPROVEMENT_LLM:-1}"
export EW_USE_ALL_CURSOR_MODELS="${EW_USE_ALL_CURSOR_MODELS:-1}"
export EW_CHEAP_FIRST="${EW_CHEAP_FIRST:-1}"
export EW_CURSOR_PRO_ONLY="${EW_CURSOR_PRO_ONLY:-1}"
export EW_ALLOW_OTHER_MODELS="${EW_ALLOW_OTHER_MODELS:-0}"
export EW_USE_CURSOR_API_POOL="${EW_USE_CURSOR_API_POOL:-0}"
export EW_LLM_CHEAP_TARGET_PCT="${EW_LLM_CHEAP_TARGET_PCT:-98}"
export EW_OTHER_MODELS_BUDGET_PCT="${EW_OTHER_MODELS_BUDGET_PCT:-2}"
export EW_OTHER_MODELS_SHAME_PCT="${EW_OTHER_MODELS_SHAME_PCT:-5}"
export EW_LLM_ROUTINE_INTELLIGENCE="${EW_LLM_ROUTINE_INTELLIGENCE:-single}"
export EW_LLM_EW_BYPASS="${EW_LLM_EW_BYPASS:-1}"
export EW_MINIMIZE_GPT="${EW_MINIMIZE_GPT:-1}"
export EW_LLM_ADVISORY="${EW_LLM_ADVISORY:-1}"
export EW_UNIVERSE_LLM_MAX="${EW_UNIVERSE_LLM_MAX:-3}"
export EW_LLM_INTELLIGENCE="${EW_LLM_INTELLIGENCE:-ensemble}"
export EW_USE_GROK_HIGH="${EW_USE_GROK_HIGH:-1}"

exec python3 scripts/run_universe_247.py "$@"
