name: dmarc-keepalive

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: gautamkrishnar/keepalive-workflow@v2
